server:
  port: 5001

eureka:
  client:
    #是否从注册中心抓取服务信息
    fetch-registry: false
    #是否将此服务注册到注册中心
    register-with-eureka: true
    #eureka的地址
    service-url:
      defaultZone: http://localhost:7961/eureka/
  instance:
    prefer-ip-address: true


spring:
  application:
    name: blog-integral
  redis:
    host: 47.115.36.38
    port: 6379
    password: myredis_123
    timeout: 3000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8


# 插件配置 pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


reids-primary:
  host: 95.169.19.152

redis-second:
  host: 47.115.36.38


logging:
  level:
    com.eva.mapper : debug

