server:
  port: 6001

eureka:
  client:
    #是否从注册中心抓取服务信息
    fetch-registry: false
    #是否将此服务注册到注册中心
    register-with-eureka: true
    #eureka的地址
    service-url:
      defaultZone: http://localhost:7961/eureka/
  instance:
    prefer-ip-address: true


spring:
  application:
    name: blog-admin
  datasource:
    username: root
#    123456 root jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: Hzy_a1234567890123
    url: jdbc:mysql://95.169.19.152:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 95.169.19.152
    port: 6379
    password: myredis_123
    timeout: 3000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.eva.dto
