server:
  port: 1000
spring:
  application:
    name: blog-zuul
  redis:
    host:  95.169.19.152
    port: 6379
ribbon:
  ReadTimeout : 12000
  ConnectTimeout : 12000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7961/eureka/
  instance:
    instance-id: zuul1000.com
    perfer-ip-address: true

zuul:
  routes:
    blog-controller-admin.serviceId : controller-admin
    blog-controller-admin.path : /ad/**
    blog-controller-user.serviceId : controller-user
    blog-controller-user.path : /user/**
  host:
    connect-timeout-millis: 12000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 12000  #socket超时
  #  隐藏controller-admin的服务名，调用controller-admind的接口用/blog/
  #  如果 是"*" 就是隐藏 全部
  ignored-services: "*"
#  prefix: /blog
#  ignored-patterns: /**/hello/**

#urlList :
#  127.0.0.1


