server:
  port: 7961

eureka:
  instance:
    #注册中心的服务机器名
    hostname: localhost
  client:
    #是否从注册中心抓取服务信息
    fetch-registry: false
    #是否将此服务注册到注册中心
    register-with-eureka: false
    #eureka的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/