server:
  port: 1001

eureka:
  client:
    #是否从注册中心抓取服务信息
    fetch-registry: true
    #是否将此服务注册到注册中心
    register-with-eureka: true
    #eureka的地址
    service-url:
      defaultZone: http://localhost:7961/eureka/
  instance:
    prefer-ip-address: true


spring:
  application:
    name: controller-admin
  redis:
    port: 6379
    lettuce:
      pool:
        max-active: 500
        max-wait: 500
        max-idle: 500
        min-idle: 0
    timeout: 500
    host: 95.169.19.152

ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true
